### ISSUE TITLE
Playtesting bugs

### ISSUE THREAD

**Issue by jmcduff** [The-GameDJs/CostumeCurse#92]
I've playtested with my sister. We visited the great tree, the shack, the farm, the view on the village and the village. Here's what we found:

- [x] We still don't have colliders to stop the player from going into mountains/falling into pits

- [x] Pumpkins/Pimpkins are used interchangeably/inconsistently? in the dialogue

- [x] Camera sometimes goes through mountains

- [x] The camera at the campfire is broken

- [x] At the lost tree, you can talk to the tree at a distance where you can't see it yet so the dialogue gets displayed but you can't see the tree's bubbles cause they're positioned at a spot where you can't see them

- [x] My sister had a lot of trouble getting out of the shack's doorway because Ganiel was blocking the way

- [x] At the spot where you can talk to a ghost who's looking at the village from afar and there's a camera change, when you go in front of the ghost the camera angle reverts back and it's a bit awkward

- [x] Who's talking during dialogue is not always clear. My sister would have liked the name to be displayed or a change in colour in the bubble, although I'm aware we may not have time for this.

**Comment by Lerihan** [comment]
Fixes from AFTER submitting:
- [ ] Ice Skeleton don't take damage
- [ ] We need to move the CrossFace image in the middle of the screen (right now it's in the corner)
- [ ] Confection panel is currently relative to Ganiel's position. Move it to the middle of the screen.
- [ ] When pausing in Main_Scene, if we press restart level it brings us to the victory screen.
- [ ] There is no pause button in the Prologue Scene
- [ ] Add corresponding music (Boss, Main Menu, Prologue, Fight ?)
